### PR TITLE
Add Node Essential Kit

### PR DESCRIPTION
**Pull request by ichtrojan**
- [ ] I have read [Contribution Guidelines](https://github.com/reyronald/awesome-toolkits/blob/master/CONTRIBUTING.md) and followed everything.
- [ ] I have an appropriate description with correct grammar.

**[what you are adding here, with a link]**

[Brief comments on why you think this should be added]

### CODE REVIEW

**Comment by reyronald** [comment]
Hi @ichtrojan ! Thank you for your suggestion!

This seems more of a boilerplate than a zero-configuration toolkit, since once you clone the repo, the user is completely disconnected from the original environment and is on its own. Not sure if we should include it in this list  😕

**Comment by ichtrojan** [comment]
yeah it is a boiler plate

**Comment by reyronald** [comment]
Check out https://github.com/melvin0008/awesome-projects-boilerplates, maybe it'll be better suited there!

Also found this with a quick Google search: http://awesomeboilerplates.com/

**Comment by ichtrojan** [comment]
seen

**Pull request closed without merging**
